export default class CommonConstant {
  static readonly FONT_WEIGHT_LARGE: number = 700
  static readonly FONT_WEIGHT: number = 500
  static readonly TITLE_WIDTH: string = '86%'
  static readonly IMAGE_BORDER_RADIUS: number = 12;
  static readonly FULL_WIDTH: string = '100%'
  static readonly FULL_HEIGHT: string = '100%'
  static readonly TARGET_BORDER_RADIUS: number = 24;
  static readonly TARGET_MARGIN_LEFT: string = '5%';
  static readonly OPACITY: number = 0.4;
  static readonly STROKE_WIDTH: number = 4.8;
}